import { neon } from "@neondatabase/serverless";
import "dotenv/config";
import { drizzle } from "drizzle-orm/neon-http";

import * as schema from "@/db/schema";

const sql = neon(process.env.DATABASE_URL);
const db = drizzle(sql, { schema });

const main = async () => {
  try {
    console.log("Seeding database");

    // Delete all existing data
    // await Promise.all([
    //   db.delete(schema.userProgress),
    //   db.delete(schema.challengeOptions),
    //   db.delete(schema.challenges),
    //   db.delete(schema.lessons),
    //   db.delete(schema.units),
    //   db.delete(schema.courses),
    // ]);

    // Insert courses
    

    // For each course, insert units
    
      const units = await db
        .insert(schema.units)
        .values([
          {
            courseId: 10,
            id:5,
            title: "Capital Market",
            description: "Understand various aspects of capital market and its implications.",
            order: 5,
          },
        ])
        .returning();

      // For each unit, insert lessons
      for (const unit of units) {
        const lessons = await db
          .insert(schema.lessons)
          .values([
            { unitId: unit.id, title: "Understanding capital market Basics", order: 1, id:9 },
            { unitId: unit.id, title: "Deep dive into capital markets", order: 2, id:10 },
          ])
          .returning();
        }
// Challenges and options for "Capital Markets" Lesson 1
const capitalMarketsLesson1Challenges = [
    {
      lessonId: 9,
      id: 41,
      type: 'SELECT' as 'SELECT', 
      question: "What is the primary function of capital markets?",
      order: 1,
    },
    {
      lessonId: 9,
      id: 42,
      type: 'SELECT' as 'SELECT', 
      question: "Which of the following is NOT a primary market activity?",
      order: 2,
    },
    {
      lessonId: 9,
      id: 43,
      type: 'SELECT' as 'SELECT', 
      question: "What is a 'secondary market'?",
      order: 3,
    },
    {
      lessonId: 9,
      id: 44,
      type: 'SELECT' as 'SELECT', 
      question: "Which of the following best describes a 'bear market'?",
      order: 4,
    },
    {
      lessonId: 9,
      id: 45,
      type: 'SELECT' as 'SELECT', 
      question: "What is 'market capitalization'?",
      order: 5,
    }
  ];
  
  const capitalMarketsLesson1Options = [
    {
      challengeId: 41,
      options: [
        { correct: false, text: "A) To facilitate short-term borrowing and lending." },
        { correct: true, text: "B) To enable companies to raise long-term funds by issuing securities." },
        { correct: false, text: "C) To provide a platform for currency exchange." },
        { correct: false, text: "D) To offer insurance and pension products." },
      ],
    },
    {
      challengeId: 42,
      options: [
        { correct: false, text: "A) Initial Public Offering (IPO)" },
        { correct: false, text: "B) Private placements" },
        { correct: true, text: "C) Trading of previously issued bonds" },
        { correct: false, text: "D) Rights issue" },
      ],
    },
    {
      challengeId: 43,
      options: [
        { correct: false, text: "A) The market where new securities are issued and sold for the first time." },
        { correct: true, text: "B) The market where existing securities are bought and sold among investors." },
        { correct: false, text: "C) The market where companies raise funds through private equity." },
        { correct: false, text: "D) The market where commodities are traded." },
      ],
    },
    {
      challengeId: 44,
      options: [
        { correct: false, text: "A) A market where stock prices are generally rising." },
        { correct: true, text: "B) A market where there is a prolonged decline in stock prices." },
        { correct: false, text: "C) A market characterized by high trading volumes and volatility." },
        { correct: false, text: "D) A market where government bonds are in high demand." },
      ],
    },
    {
      challengeId: 45,
      options: [
        { correct: true, text: "A) The total value of a company's outstanding shares of stock." },
        { correct: false, text: "B) The total amount of debt a company has issued." },
        { correct: false, text: "C) The total amount of equity a company has in its balance sheet." },
        { correct: false, text: "D) The total revenue generated by a company in a fiscal year." },
      ],
    }
  ];
  
// Challenges and options for "Capital Markets" Lesson 2
const capitalMarketsLesson2Challenges = [
    {
      lessonId: 10,
      id: 46,
      type: 'SELECT' as 'SELECT', 
      question: "What does the term 'underwriting' refer to in capital markets?",
      order: 6,
    },
    {
      lessonId: 10,
      id: 47,
      type: 'SELECT' as 'SELECT', 
      question: "Which of the following is a characteristic of a 'blue-chip' stock?",
      order: 7,
    },
    {
      lessonId: 10,
      id: 48,
      type: 'SELECT' as 'SELECT', 
      question: "What is an 'exchange-traded fund' (ETF)?",
      order: 8,
    },
    {
      lessonId: 10,
      id: 49,
      type: 'SELECT' as 'SELECT', 
      question: "What is the purpose of a 'prospectus' in a public offering?",
      order: 9,
    },
    {
      lessonId: 10,
      id: 50,
      type: 'SELECT' as 'SELECT', 
      question: "Which of the following is an example of a derivative security?",
      order: 10,
    }
  ];
  
  const capitalMarketsLesson2Options = [
    {
      challengeId: 46,
      options: [
        { correct: true, text: "A) The process of issuing new securities and assuming the risk of buying them." },
        { correct: false, text: "B) The process of buying and selling existing securities on the secondary market." },
        { correct: false, text: "C) The process of auditing a company's financial statements." },
        { correct: false, text: "D) The process of assessing a company’s creditworthiness for a loan." },
      ],
    },
    {
      challengeId: 47,
      options: [
        { correct: false, text: "A) High volatility and high potential returns." },
        { correct: true, text: "B) Established companies with a history of stable earnings and dividends." },
        { correct: false, text: "C) New companies with high growth potential." },
        { correct: false, text: "D) Stocks with low trading volumes and limited market activity." },
      ],
    },
    {
      challengeId: 48,
      options: [
        { correct: true, text: "A) A type of mutual fund that trades on stock exchanges like individual stocks." },
        { correct: false, text: "B) A fund that only invests in government securities." },
        { correct: false, text: "C) A type of bond issued by a corporation." },
        { correct: false, text: "D) A fund that offers guaranteed returns and low risk." },
      ],
    },
    {
      challengeId: 49,
      options: [
        { correct: true, text: "A) To provide detailed information about the investment opportunity and associated risks." },
        { correct: false, text: "B) To outline the company's future growth projections." },
        { correct: false, text: "C) To ensure compliance with tax regulations." },
        { correct: false, text: "D) To offer a detailed analysis of the company's competitors." },
      ],
    },
    {
      challengeId: 50,
      options: [
        { correct: false, text: "A) Common stock" },
        { correct: false, text: "B) Corporate bond" },
        { correct: true, text: "C) Option contract" },
        { correct: false, text: "D) Treasury bill" },
      ],
    }
  ];
  

  for (const challenge of capitalMarketsLesson1Challenges) {
    await db.insert(schema.challenges).values(challenge);
  }
  for (const optionSet of capitalMarketsLesson1Options) {
    await db.insert(schema.challengeOptions).values(
      optionSet.options.map(option => ({ ...option, challengeId: optionSet.challengeId }))
    );
  }

  for (const challenge of capitalMarketsLesson2Challenges) {
    await db.insert(schema.challenges).values(challenge);
  }
  for (const optionSet of capitalMarketsLesson2Options ) {
    await db.insert(schema.challengeOptions).values(
      optionSet.options.map(option => ({ ...option, challengeId: optionSet.challengeId }))
    );
  }


console.log("Seeding complete");
} catch (error) {
  console.error("Error seeding database:", error);
}
};

main();
